#!/bin/bash

#$1 = '$file_name'
#$2 = '${file_base_name}'

##################A projekt paraméterei:################
fordito="g++"
projectfileok="main.cpp widgets.cpp examplecheckbox.cpp stattext.cpp"
parameterek="-std=c++14 -lgraphics -lSDL -lSDL_ttf -L."
nev="widget.run"
futtatas=true
########################################################



################Fordítás és futtatás:###################
if [[ ! -d "bin" ]]; then
	mkdir "bin"
fi

nev="bin/$nev"

if [ -f $nev ]; then ## Biztonsági mentés
    mv $nev $nev".bak";
fi

$fordito $projectfileok $parameterek "-o" $nev

if [[ $futtatas && -f $nev ]]; then
	timeout 4s gnome-terminal -x $nev;
fi
########################################################