#!/bin/bash

#$1 = '$file_name'
#$2 = '${file_base_name}'

##################A projekt paraméterei:################
fordito="g++"
projectfileok1=$(find . -name "*.cpp")
projectfileok2=""
parameterek="-std=c++14 -lSDL2"
nev="main.run"
futtatas=true
########################################################



################Fordítás és futtatás:###################
if [[ ! -d "bin" ]]; then
	mkdir "bin"
fi

nev="bin/$nev"

if [ -f $nev ]; then ## Biztonsági mentés
    mv $nev $nev".bak";
fi

$fordito $projectfileok1 $projectfileok2 $parameterek "-o" $nev

if [[ "$futtatas" = true && -f $nev ]]; then
	timeout 4s gnome-terminal -x $nev;
fi
########################################################